package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func sanitizeClassName(name string) string {
	base := filepath.Base(name)
	base = strings.TrimSuffix(base, ".joss.html")
	base = strings.TrimSuffix(base, ".joss")
	base = strings.TrimSuffix(base, ".html")
	base = strings.ReplaceAll(base, "-", "_")
	if len(base) > 0 {
		base = strings.ToUpper(base[:1]) + base[1:]
	}
	return base
}

func createController(name string) {
	path := filepath.Join("app", "controllers", name+".joss")
	os.MkdirAll(filepath.Dir(path), 0755)

	className := sanitizeClassName(name)
	viewPrefix := strings.ToLower(strings.TrimSuffix(className, "Controller"))

	var content string
	if isConsoleProject() {
		content = fmt.Sprintf(`public class %s {
    public func index() {
        print("Hello from %s")
    }
}`, className, className)
	} else {
		content = fmt.Sprintf(`public class %s {
    public func index() {
        return view("%s/index")
    }
}`, className, viewPrefix)
	}

	writeGenFile(path, content)
}

func createModel(name string) {
	path := filepath.Join("app", "models", name+".joss")
	os.MkdirAll(filepath.Dir(path), 0755)

	className := sanitizeClassName(name)
	_, _, _, _, _, _, prefix := loadEnvConfig()
	// Fix: singularize first to avoid double pluralization
	tableName := prefix + strings.ToLower(pluralize(singularize(className)))

	content := fmt.Sprintf(`public class %s extends GranDB {
    public mixed $tabla = "%s"
}`, className, tableName)

	writeGenFile(path, content)
}

func createView(name string) {
	if isConsoleProject() {
		fmt.Println("Error: Cannot create view in a console project.")
		return
	}

	// name can be "users/index"
	path := filepath.Join("app", "views", name+".joss.html")
	if !strings.HasSuffix(name, ".joss.html") && !strings.HasSuffix(name, ".html") {
		// If no extension, assume .joss.html
	} else {
		// If extension provided, use it
		path = filepath.Join("app", "views", name)
	}

	os.MkdirAll(filepath.Dir(path), 0755)

	content := fmt.Sprintf(`@extends('layouts.master')

@section('content')
    <h1>View: %s</h1>
    <p>Generated by joss make:view</p>
@endsection
`, name)

	writeGenFile(path, content)
}

func createMiddleware(name string) {
	path := filepath.Join("app", "middleware", name+".joss")
	os.MkdirAll(filepath.Dir(path), 0755)

	className := sanitizeClassName(name)
	middlewareKey := strings.ToLower(className)

	content := fmt.Sprintf(`// Middleware: %s
Router::registerMiddleware("%s", func() {
    // Middleware Logic
    // Return explicit Response to block, or nothing/true to continue
    
    // Example: Check Header
    // $auth = Request::header("Authorization")
    // (!$auth) ? { return Response::json({"error": "Unauthorized"}, 401) }
})
`, className, middlewareKey)

	writeGenFile(path, content)
}

func createMVC(name string) {
	fmt.Printf("Generating MVC for %s...\n", name)
	createModel(name)
	createController(name + "Controller")
	if !isConsoleProject() {
		createView(strings.ToLower(name) + "/index")
	}
}
